export { default as RegisterBoard } from "./RegisterBoard";
export { default as AddDropWithdrawBoard } from "./AddDropWithdrawBoard";
export { default as GradeBoard } from "./GradeBoard";
export { default as DocumentBoard } from "./DocumentBoard";
export { default as FeeBoard } from "./FeeBoard";
export { default as TimeTableBoard } from "./TimeTableBoard";
export { default as CourseBoard } from "./CourseBoard";
export { default as AdviseeBoard } from "./AdviseeBoard";
export { default as RegisterPeriodBoard } from "./RegisterPeriodBoard";
